ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS postal_code TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS legal_form TEXT,
  ADD COLUMN IF NOT EXISTS capital NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS vat_subject BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS vat_periodicity TEXT DEFAULT 'trimestrielle',
  ADD COLUMN IF NOT EXISTS fiscal_year_end TEXT,
  ADD COLUMN IF NOT EXISTS csam_date DATE,
  ADD COLUMN IF NOT EXISTS csam_duration_months INT,
  ADD COLUMN IF NOT EXISTS monthly_fee NUMERIC(8,2),
  ADD COLUMN IF NOT EXISTS gsm TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;